---
title: "NS02-vvhA-hindcast"
author: "Jessica Bullington"
date: "12/25/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r clear workspace}
rm(list=ls())
```

```{r load data}
bot.data = read.csv("AlaWai_DiscreteBottle.csv")
cont.data = read.csv("NS02_Continuous.csv")
surv.data = read.csv("NS02_SurveyValidation.csv")
disc.data = read.csv("NS02_Discrete.csv")

surv.data$Site = as.factor(surv.data$Site)
disc.data$Site = as.factor(disc.data$Site)

# transformations
bot.data$log.rain = log10(bot.data$Rainfall_5Day+0.1)
bot.data$sq.sal = (bot.data$Salinity)^2
bot.data$log.VH = log10(bot.data$VisibleHumic.like)

```


```{r load libraries}
#install.packages("packageName") if not already installed
library(ggplot2)
library(dplyr) 
library(tidyr)
```

## Compare moored NS02 to survey data 

```{r sensor data}
# define regression plot
ggplotRegression <- function (fit) {
    ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
      geom_point() +
      theme_bw() +
      theme(plot.title = element_text(hjust = 1)) +
      geom_abline(intercept = 0, slope = 1, col = "brown1") +
      stat_smooth(method = "lm", formula= y~x, col = "steelblue") +
      labs(
        x = "Survey log10(vvhA)", y = "NS02 Predicted log10(vvhA)",
             title = paste("Y =", round(fit$coef[[1]], 2),
                         "+", round(fit$coef[[2]], 2), "*X,",
                         "R^2 = ", round(summary(fit)$r.squared, 2)))
}

# subset by site
surv.data3 = subset(surv.data, Site == "3")
surv.data2 = subset(surv.data, Site == "2")

# subset by depth
around.1m = c("0.75-1 m", "1-1.25 m", "1.25-1.5 m", "1.5-1.75 m", "1.75-2 m")
surv.data3.1m = subset(surv.data3, Survey_depth_bin %in% around.1m)
surv.data2.1m = subset(surv.data2, Survey_depth_bin %in% around.1m)

# water temperature
temp = lm(NS02_temperature.C ~ Survey_Temperature, data = surv.data)

temp3 = lm(NS02_temperature.C ~ Survey_Temperature, data = surv.data3) # site 3
temp2 = lm(NS02_temperature.C ~ Survey_Temperature, data = surv.data2) # site 2

temp3.1m = lm(NS02_temperature.C ~ Survey_Temperature, data = surv.data3.1m) # site 3 at ~ 1m
temp2.1m = lm(NS02_temperature.C ~ Survey_Temperature, data = surv.data2.1m) # site 2 at ~ 1m

ggplot(surv.data2.1m, aes(Survey_Temperature,NS02_temperature.C, col= Month)) +
       geom_point()

ggplotRegression(temp)
ggplotRegression(temp3)
ggplotRegression(temp2)
ggplotRegression(temp3.1m) # best
ggplotRegression(temp2.1m)

# salinity
sal = lm(NS02_salinity.PSU ~ Survey_Salinity, data = surv.data)

ggplot(surv.data3.1m, aes(Survey_Salinity,NS02_salinity.PSU, col= Month)) +
       geom_point()
       

sal3 = lm(NS02_salinity.PSU ~ Survey_Salinity, data = surv.data3) # site 3
sal2 = lm(NS02_salinity.PSU ~ Survey_Salinity, data = surv.data2) # site 2

sal3.1m = lm(NS02_salinity.PSU ~ Survey_Salinity, data = surv.data3.1m) # site 3 at ~ 1m
sal2.1m = lm(NS02_salinity.PSU ~ Survey_Salinity, data = surv.data2.1m) # site 2 at ~ 1m

ggplotRegression(sal)
ggplotRegression(sal3)
ggplotRegression(sal2)
ggplotRegression(sal3.1m)
ggplotRegression(sal2.1m) # best but no great

```


```{r discrete bottle data}
# subset by site and sample depth

# site 3
oct = subset(disc.data, Site == "3" & SampleDepth == "Bottom" & Day == "10/20/18")
nov = subset(disc.data, Site == "3" & SampleDepth != "Surface" & Day == "11/29/18")
jan = subset(disc.data, Site == "3" & SampleDepth != "Bottom" & Day == "1/20/19")
feb = subset(disc.data, Site == "3" & SampleDepth == "Surface" & Day == "2/18/19")
mar = subset(disc.data, Site == "3" & SampleDepth == "Surface" & Day == "3/22/19")
apr = subset(disc.data, Site == "3" & SampleDepth != "Surface" & Day == "4/20/19")

disc.data.3 = rbind(oct, nov, jan, feb, mar, apr)

disc.data.3$log_Survey_VisibleHumic.like = log10(disc.data.3$Survey_VisibleHumic.like)
disc.data.3$log_FLNTU_fDOM_raw = log10(disc.data.3$FLNTU_fDOM_raw)

fdom1 = lm(FLNTU_fDOM_raw ~ Survey_VisibleHumic.like, data = disc.data.3)
ggplotRegression(fdom1) 

fdom2 = lm(FLNTU_fDOM_raw ~ log_Survey_VisibleHumic.like, data = disc.data.3)
ggplotRegression(fdom2) 

fdom3 = lm(log_FLNTU_fDOM_raw ~ log_Survey_VisibleHumic.like, data = disc.data.3) # best
ggplotRegression(fdom3) # best

# convert raw fdom to VH
fdom3.convert = lm(log_Survey_VisibleHumic.like ~ log_FLNTU_fDOM_raw, data = disc.data.3) 
ggplotRegression(fdom3.convert) 

disc.data.3$log_FLNTU_VH = coef(fdom3.convert)[1] + (coef(fdom3.convert)[2]*log10(disc.data.3$FLNTU_fDOM_raw))
fdom3.1 = lm(log_FLNTU_VH ~ log_Survey_VisibleHumic.like, data = disc.data.3) # best
ggplotRegression(fdom3.1) 

# site 2
disc.data.2 = subset(disc.data, Site == "2" & SampleDepth == "Surface" & Day != "10/21/18")

disc.data.2$log_Survey_VisibleHumic.like = log10(disc.data.2$Survey_VisibleHumic.like)
disc.data.2$log_FLNTU_fDOM_raw = log10(disc.data.2$FLNTU_fDOM_raw)

fdom4 = lm(FLNTU_fDOM_raw ~ Survey_VisibleHumic.like, data = disc.data.2)
ggplotRegression(fdom4) 

fdom5 = lm(FLNTU_fDOM_raw ~ log_Survey_VisibleHumic.like, data = disc.data.2)
ggplotRegression(fdom5) 

fdom6 = lm(log_FLNTU_fDOM_raw ~ log_Survey_VisibleHumic.like, data = disc.data.2)
ggplotRegression(fdom6) 

```

```{r export regression plots}
a = ggplotRegression(temp2.1m)
b = ggplotRegression(sal2.1m) 
c = ggplotRegression(fdom3.1)
l = mget(c("a", "c", "b"))
ggsave("NS02_validation.pdf", marrangeGrob(grobs = l, nrow=2, ncol=2),
       units = "cm",
       width = 21,
       height = 20,
       dpi = 300)

```


## Predict vvhA

```{r predict vvhA for discrete NS02 data and compare to survey}
disc.data.2 = subset(disc.data, Site == "2" & SampleDepth == "Surface") 
disc.data.2$log_FLNTU_VH = coef(fdom3.convert)[1] + (coef(fdom3.convert)[2]*log10(disc.data.2$FLNTU_fDOM_raw))
disc.data.2 = na.omit(disc.data.2) # compare model fit to same data

# regression for equation without fDOM
mod1 = lm(log10(vvhA) ~ log.rain + AirTemp_Max + sq.sal + WaterTemp, data = bot.data) 

# predict vvhA for discrete without fDOM
new.data = data.frame(log10(disc.data.2$Survey_Rainfall_5Day+0.1), disc.data.2$Survey_AirTemp_Max, (disc.data.2$NS02_salinity.PSU)^2, disc.data.2$NS02_temperature.C)

new.data = new.data %>%
  rename(log.rain=log10.disc.data.2.Survey_Rainfall_5Day...0.1., AirTemp_Max=disc.data.2.Survey_AirTemp_Max,
         sq.sal=X.disc.data.2.NS02_salinity.PSU..2, WaterTemp=disc.data.2.NS02_temperature.C)

pred1.CI = predict(mod1, newdata = new.data, interval = "confidence")
pred1.PI = predict(mod1, newdata = new.data, interval = "prediction")

# compare predicted to observed vvhA without fDOM
surv.vvhA = log10(disc.data.2$Survey_vvhA)

vvhA.compare = data.frame(surv.vvhA, pred1.CI, pred1.PI)

mod.comp = lm(fit ~ surv.vvhA, data=vvhA.compare)
ggplotRegression(mod.comp) 

rmse.1 = round(sqrt(sum(vvhA.compare$surv.vvhA - vvhA.compare$fit)^2)/nrow(vvhA.compare), 2)


# regression for equation with fDOM
mod2 = lm(log10(vvhA) ~ log.rain + AirTemp_Max + sq.sal + WaterTemp + log.VH, data = bot.data) 

# predict vvhA for discrete with fDOM
new.data2 = data.frame(log10(disc.data.2$Survey_Rainfall_5Day+0.1), disc.data.2$Survey_AirTemp_Max, (disc.data.2$NS02_salinity.PSU)^2, disc.data.2$NS02_temperature.C, disc.data.2$log_FLNTU_VH)

new.data2 = new.data2 %>% rename(log.rain=log10.disc.data.2.Survey_Rainfall_5Day...0.1., AirTemp_Max=disc.data.2.Survey_AirTemp_Max, sq.sal=X.disc.data.2.NS02_salinity.PSU..2, WaterTemp=disc.data.2.NS02_temperature.C, log.VH=disc.data.2.log_FLNTU_VH)

pred2.CI = predict(mod2, newdata = new.data2, interval = "confidence")
pred2.PI = predict(mod2, newdata = new.data2, interval = "prediction")

# compare predicted to observed vvhA with fDOM
surv.vvhA = log10(disc.data.2$Survey_vvhA)

vvhA.compare2 = data.frame(surv.vvhA, pred2.CI, pred2.PI)

mod.comp2 = lm(fit ~ surv.vvhA, data=vvhA.compare2)
ggplotRegression(mod.comp2) 

rmse.2 = round(sqrt(sum(vvhA.compare2$surv.vvhA - vvhA.compare2$fit)^2)/nrow(vvhA.compare2), 2)

```

```{r export vvhA prediction plots}
e = ggplotRegression(mod.comp)
d = ggplotRegression(mod.comp2) 

l = mget(c("e", "d"))
ggsave("vvhA_validation.pdf", marrangeGrob(grobs = l, nrow=1, ncol=2),
       units = "cm",
       width = 21,
       height = 10,
       dpi = 300)

```


```{r predict vvhA for full year of continuous data}
cont.data$log_FLNTU_VH = coef(fdom3.convert)[1] + (coef(fdom3.convert)[2]*log10(cont.data$FLNTU_fDOM_raw))

new.data.year = data.frame(log10(cont.data$NOAA_Rainfall_5Day+0.1), cont.data$NOAA_AirTemperature_Max, (cont.data$NS02_salinity)^2, cont.data$NS02_temperature, cont.data$log_FLNTU_VH)

new.data.year = new.data.year %>% rename(log.rain=log10.cont.data.NOAA_Rainfall_5Day...0.1., AirTemp_Max=cont.data.NOAA_AirTemperature_Max, sq.sal=X.cont.data.NS02_salinity..2, WaterTemp=cont.data.NS02_temperature, log.VH=cont.data.log_FLNTU_VH)

# without fDOM
pred.year.CI1 = predict(mod1, newdata = new.data.year, interval = "confidence")
pred.year.PI1 = predict(mod1, newdata = new.data.year, interval = "prediction")

# with fDOM
pred.year.CI2 = predict(mod2, newdata = new.data.year, interval = "confidence")
pred.year.PI2 = predict(mod2, newdata = new.data.year, interval = "prediction")

cont.vvhA = data.frame(cont.data, pred.year.CI1, pred.year.CI2)

```


```{r plot the predictors and vvhA over the sampling year}
sample = c(1540159200,1543528800,1548021600, 1550527200, 1553292000, 1555797600, 1559685600,1567288800,1569794400)
refs = c("Oct-2018", "Nov", "Jan", "Feb", "Mar", "Apr", "Jun", "Aug", "Sep-2019")
cuts <- data.frame(sample,refs,stringsAsFactors = FALSE)

# air temp
f = ggplot(cont.vvhA, aes(TimeStamp, NOAA_AirTemperature_Max)) +
  geom_line(aes(y = NOAA_AirTemperature_Max), color = "pink", size =0.5) +
  scale_y_continuous(limits = c(23,36))+
  labs(y="Air Temperature") +
  scale_x_continuous(limits = c(1538431200, 1569967200))+
  geom_vline(xintercept = sample, linetype = "dashed")+
  theme_classic()+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank()) 

# water temp
g = ggplot(cont.vvhA, aes(TimeStamp, NS02_temperature)) +
  geom_line(aes(y = NS02_temperature), color = "red", size =0.25) +
  scale_y_continuous(limits = c(23,36))+
  labs(y="Water Temperature")+
  scale_x_continuous(limits = c(1538431200, 1569967200))+
  geom_vline(xintercept = sample, linetype = "dashed")+
  theme_classic()+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank()) 

# rainfall
h = ggplot(cont.vvhA, aes(TimeStamp, NOAA_Rainfall)) +
  geom_line(aes(y = NOAA_Rainfall_5Day), color = "lightblue", size =0.5) +
  scale_y_continuous(limits = c(0,40))+
  labs(y="Daily Rainfall")+
  scale_x_continuous(limits = c(1538431200, 1569967200))+
  geom_vline(xintercept = sample, linetype = "dashed")+
  theme_classic() +
  theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank()) 

# salinity
i = ggplot(cont.vvhA, aes(TimeStamp, NS02_salinity)) +
  geom_line(aes(y = NS02_salinity), color = "blue", size =0.25) +
  scale_y_continuous(limits = c(15,35))+
  labs(y="Salinity")+
  scale_x_continuous(limits = c(1538431200, 1569967200))+
  geom_vline(xintercept = sample, linetype = "dashed")+
  theme_classic()+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank()) 

# vvhA model 3
j = ggplot(cont.vvhA, aes(TimeStamp, fit)) +
  geom_line(aes(y = fit), color = "purple", size =0.25) +
  scale_y_continuous(limits = c(-1,3))+
  geom_ribbon(aes(ymin = lwr, ymax = upr), alpha = 0.5) +
  labs(y="Model 3 log10(vvhA)")+
  scale_x_continuous(limits = c(1538431200, 1569967200))+
  geom_vline(xintercept = sample, linetype = "dashed")+
  theme_classic()+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank()) 

# fdom
k = ggplot(cont.vvhA, aes(TimeStamp, log_FLNTU_VH)) +
  geom_line(aes(y = log_FLNTU_VH), color = "darkgreen", size =0.25) +
  scale_y_continuous(limits = c(-2,1))+
  labs(y="log10(DOM)")+
  scale_x_continuous(limits = c(1538431200, 1569967200))+
  geom_vline(xintercept = sample, linetype = "dashed")+
  theme_classic()+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank()) 

# vvhA model 5
n = ggplot(cont.vvhA, aes(TimeStamp, fit.1)) +
  geom_line(aes(y = fit.1), color = "purple", size =0.25) +
  scale_y_continuous(limits = c(-1,3))+
  geom_ribbon(aes(ymin = lwr.1, ymax = upr.1), alpha = 0.5) +
  labs(x = " ", y="Model 5 log10(vvhA)")+
  scale_x_continuous(limits = c(1538431200, 1569967200))+
  geom_vline(xintercept = sample, linetype = "dashed")+
  theme_classic()+
  theme( axis.text.x = element_blank(), axis.ticks.x = element_blank())

l = mget(c("f", "g", "h", "i", "j", "k", "n"))
ggsave("NS02_full_timeseries.pdf", marrangeGrob(grobs = l, nrow=7, ncol=1),
       units = "cm",
       width = 21,
       height = 30,
       dpi = 300)
```

